# name: 'Terraform CI/CD'

# on:
#   push:
#     branches:
#       - master

# jobs:
#   terraform:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Set up AWS CLI
#       uses: aws-actions/configure-aws-credentials@v2
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-east-2

#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v3

#     - name: Terraform Init
#       run: terraform init

#     - name: Terraform Validate
#       run: terraform validate

#     - name: Terraform Plan
#       id: plan
#       run: terraform plan -out=tfplan

#     - name: Review Terraform Plan
#       run: echo "Review the Terraform plan output"

#     - name: Manual Approval
#       id: approval
#       uses: trstringer/manual-approval@v1
#       with:
#         secret: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
#         approvers: "chandradeoarya"
#         minimum-approvals: 1
#         issue-title: "Deploying new infra to test using tf"
#         issue-body: "Please approve or deny the deployment of latest tf apply."
#         exclude-workflow-initiator-as-approver: false
#         additional-approved-words: 'yes'
#         additional-denied-words: ''
        
#     - name: Terraform Apply
#       run: terraform apply tfplan